server:
  port: 3002
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://codetattoo.cwtbzbyluijp.ap-northeast-2.rds.amazonaws.com/Chat_Data?serverTimezone=Asia/Seoul
    username: codeTattoo
    password: 12345678
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update