export const genre = [
  { text: '두피문신', name: 'scalp' },
  { text: '눈썹문신', name: 'eyebrow' },
  { text: '올드스쿨', name: 'oldSchool' },
  { text: '뉴스쿨', name: 'newSchool' },
  { text: '재패니즈', name: 'japanese' },
  { text: '블랙엔그레이', name: 'blackAndGrey' },
  { text: '다크사이드', name: 'darkSide' },
  { text: '트래쉬 폴카', name: 'trashPolka' },
  { text: '치카노', name: 'chicano' },
  { text: '블랙워크', name: 'blackWork' },
  { text: '라인워크', name: 'lineWork' },
  { text: '폴리네시안', name: 'polynesian' },
  { text: '컬러', name: 'color' },
  { text: '수채화', name: 'waterColor' },
  { text: '커스텀 레터링', name: 'customLettering' },
  { text: '직접입력', name: 'selfInput' },
]

export const keywords = [
  { text: '꽃', name: 'flower' },
  { text: '고래', name: 'whale' },
  { text: '장미', name: 'rose' },
  { text: '뱀', name: 'snake' },
  { text: '나침반', name: 'compass' },
  { text: '동물', name: 'animal' },
  { text: '인물', name: 'person' },
  { text: '용', name: 'dragon' },
  { text: '반려동물', name: 'pet' },
  { text: '종교', name: 'religion' },
  { text: '해골', name: 'skull' },
  { text: '가족', name: 'family' },
]

export const drafts = [
  {
    draft_id: 1,
    image: '../../img/ex.jpg',
    title: 'express',
    like: 3,
    isScraped: true,
    drawer_id: 10,
    drawer_image: '../../img/ex.jpg',
    drawer_nickname: 'ahyoung',
  },
  {
    draft_id: 2,
    image: '../../img/react.jpg',
    title: 'react',
    like: 31,
    isScraped: false,
    drawer_id: 20,
    drawer_image: '../../img/react.jpg',
    drawer_nickname: 'minsoo',
  },
  {
    draft_id: 3,
    image: '../../img/react.jpg',
    title: 'react',
    like: 31,
    isScraped: false,
    drawer_id: 30,
    drawer_image: '../../img/react.jpg',
    drawer_nickname: 'minsoo',
  },
  {
    draft_id: 4,
    image: '../../img/react.jpg',
    title: 'react',
    like: 31,
    isScraped: false,
    drawer_id: 40,
    drawer_image: '../../img/react.jpg',
    drawer_nickname: 'minsoo',
  },
  {
    draft_id: 5,
    image: '../../img/react.jpg',
    title: 'react',
    like: 31,
    isScraped: true,
    drawer_id: 50,
    drawer_image: '../../img/react.jpg',
    drawer_nickname: 'minsoo',
  }
];